---
title: "snail experiment"
author: "Noam Altman-Kurosaki"
date: "2024-11-08"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls()) # clean up
librarian::shelf(knitr, plyr, tidyr, dplyr, effects, ggplot2, ggrepel, ggpubr, emmeans, DHARMa, glmmTMB, MuMIn, survival, coxme, car, lattice)
opts_chunk$set(comment="  ",
               collapse=TRUE, 
               echo=FALSE,
               dev="png",
               warning=TRUE
               )
```

```{r functions}
# smithson verkuilen transformation for 0-1 continuous data
sv_trans <- function(prop, s = 0.000005){
  (prop*(length(prop) - 1) + s)/length(prop)
  # where prop is the vector of the proportional value you're transforming, 
  # N is the sample size, which is specified by taking the number of rows/observations from a given dataframe,
  # and s is a small offset 
}
```

```{r ggplot themes}
# set order, labels, and coloring for commonly used species
coral_labels <- c(expression(italic("Pocillopora")), expression(italic("Porites")))
coral_limits <- c("Pocillopora", "Porites")
coral_colors <-  c("Pocillopora" = "#0072B2", "Porites" = "#D55E00")


snail_labels <- c("Control", expression(italic("Coralliophila")), expression(italic("Drupella")))
snail_limits <- c("Control", "Coralliophila", "Drupella")
snail_colors <- c("Control" = "grey20", "Coralliophila" = "darkviolet", "Drupella" = "dodgerblue2")

# Theme for plots
my_theme <-
  theme_classic() + 
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        legend.position = "bottom",
        legend.key.size = unit(1.5, 'cm'),
        legend.text = element_text(size=25),
        legend.title = element_text(size=32),
        axis.line = element_line(colour = "black"),
        plot.title = element_text(color = "black", size = 32, face = "plain"),
        axis.text.x = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        axis.text.y = element_text(color = "black", size = 30, hjust = .5, vjust = .5, face = "plain"),
        axis.title.y = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain"),
        strip.text.x = element_text(color = "black", size = 32, hjust = .5, vjust = 0, face = "plain")
  )

```

```{r choice assay}
choice <-read.csv(here::here("data", "snail_choice_assay.csv"))

# pivot longer
choice_long <- choice %>%
  pivot_longer(
    cols = c(Porites, Pocillopora, NC), # Columns representing choices
    names_to = "Prey",                 # Name for the new column for choices
    values_to = "Choice"               # Name for the new column for values
  )

# convert to contingency table
contingency_table <- choice_long %>%
  group_by(Snail, Prey) %>%
  summarize(Count = sum(Choice, na.rm = T)) %>%
  pivot_wider(names_from = Prey, values_from = Count, values_fill = 0)

# convert to matrix for fisher's exact test
contingency_table_m <- as.matrix(contingency_table[,-which(names(contingency_table) %in% "Snail")])
fisher.test(contingency_table_m) # P = 5.29E-05
```

```{r plot choice assay, fig.height=15, fig.width=15}
# prepare data for plotting
proportions <- choice_long %>%
  group_by(Snail, Prey) %>%
  summarize(Count = sum(Choice, na.rm = T)) %>%
  group_by(Snail) %>%
  mutate(Proportion = Count / sum(Count))

# Plot
(choice_plot <-
  ggplot(proportions, aes(x = Snail, y = Proportion, fill = Prey)) +
  geom_bar(stat = "identity") +
  geom_text(aes(x = 0.55, y = 1.15, label = "Fisher's Exact Test\nn = 15\nP < 0.0001"), hjust = 0, size = 14) +
  scale_fill_manual(values = c("NC" = "darkgrey",
                               "Pocillopora" = "#0072B2",
                               "Porites" = "#D55E00"),
                    labels = c("No Choice", coral_labels)) +
  labs(x = "", y = "Proportion of Choices\n", fill = "Prey") +
  scale_y_continuous(expand = expansion(mult = c(0, 0.1)),
                     breaks = seq(0, 1, 0.25)) +  
  scale_x_discrete(labels = c("Coralliophila" = expression(italic(Coralliophila)), "Drupella" = expression(italic(Drupella)))) +
  my_theme)

# ggsave(here::here("output", "snail_choice_plot_v1.png"), choice_plot, height = 15, width = 15)
```

```{r  respo unfed snails}
respo <- read.csv(here::here("data", "snail_respo.csv"))

unfed <- subset(respo, Trial.type == "Unfed")
fed <- subset(respo, Trial.type == "Fed")

unfed_mod <- glmmTMB(abs(Respiration) ~ Snail*Temp, data = unfed, family = Gamma(link = "log"))
summary(unfed_mod)
Anova(unfed_mod)
#              Chisq Df Pr(>Chisq)    
# Snail      18.8110  1  1.443e-05 ***
# Temp        3.7143  1    0.05395 .  
# Snail:Temp  0.7323  1    0.39214    
plot(simulateResiduals(unfed_mod)) # no issues
plot(allEffects(unfed_mod))
emmeans(unfed_mod, pairwise ~ Temp | Snail) # despite no sig interaction, Drupella respo still increased in heated
# $contrasts
# Snail = Coralliophila:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.249 0.328 Inf  -0.758  0.4487
# 
# Snail = Drupella:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.646 0.328 Inf  -1.968  0.0491
 



fed_mod <- glmmTMB(abs(Respiration) ~ Temp*Snail + (1|Tank), data = fed, family = Gamma(link = "log"))
summary(fed_mod)
plot(simulateResiduals(fed_mod)) # issues in QQ residuals
bwplot(abs(Respiration) ~ Temp | Snail, data = fed) # driven by outliers from heated treat. I don't want to delete them
hist(residuals(fed_mod), breaks = 20)
plot(predict(fed_mod) ~ residuals(fed_mod)) # yeah. I think I'm fine with this

# NOTE: I tested this on a subset that removed these outliers. The issues were lessened but not fully removed
# However, the trends were identical (though temp effect was slightly lessened)
Anova(fed_mod)
# Response: abs(Respiration)
#              Chisq Df Pr(>Chisq)    
# Temp        5.2148  1     0.0224 *  
# Snail      28.8189  1  7.947e-08 ***
# Temp:Snail  1.4790  1     0.2239    
plot(allEffects(fed_mod))
emmeans(fed_mod, pairwise ~ Temp | Snail) # Coralliophila resp doesn't increase with temp but Drup does
# $contrasts
# Snail = Coralliophila:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.181 0.159 Inf  -1.142  0.2533
# 
# Snail = Drupella:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.405 0.158 Inf  -2.567  0.0103

emmeans(fed_mod, pairwise ~ Snail | Temp) # Drup resp always higher than Coralliophila
# $contrasts
# Temp = Ambient:
#  contrast                 estimate    SE  df z.ratio p.value
#  Coralliophila - Drupella   -0.380 0.131 Inf  -2.915  0.0036
# 
# Temp = Heated:
#  contrast                 estimate    SE  df z.ratio p.value
#  Coralliophila - Drupella   -0.604 0.129 Inf  -4.670  <.0001


  
```

```{r plot respiration, fig.height = 10, fig.width=12}

(respo_plot <- ggplot() +
  geom_boxplot(data = fed, aes(x = Snail, y = abs(Respiration), colour = Temp), outlier.shape = NA) +
  geom_point(data = fed,
             aes(x = Snail, y = abs(Respiration), colour = Temp), position = position_jitterdodge(0.3)) +
  scale_y_continuous(trans = "log10") +
  scale_colour_manual(values = c("Heated" = "#FE6100", "Ambient" = "#648FFF"),
                      labels = c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)")) +
  scale_x_discrete(labels = c("Coralliophila" = expression(atop(italic("Coralliophila"), "n = 53")),
                              "Drupella" = expression(atop(italic("Drupella"), "n = 54"))
                              )
                   ) +
  labs(y = expression(Respiration ~ (mu * mol ~ O[2] ~ g ~ h^-1)), x = "") +
  geom_segment(aes(x = 1.8, xend = 2.2, y = 3.5, yend = 3.5)) +
  geom_text(aes(x = 2, y = 3.7, label = "*"), size = 14) +
  geom_text(aes(x = 0.5, y = 3, label = "Temp: P = 0.022\nSnail: P < 0.0001\nInteraction: P = 0.22"), hjust = 0, size = 10) + 
  my_theme)

# ggsave(here::here("output", "respiration_plot_v1.png"), respo_plot, height = 10, width = 12)
```

```{r growth}
# read data
growth <- read.csv(here::here("data", "coral_weights.csv"), stringsAsFactors = T)

# extract meta for future merges
growth_meta <- growth[,which(names(growth) %in% c("Coral.ID", "Coral.species", "Treatment", "Snail", "Colony.ID", "Tank"))]

# subset for each species
pocillopora <- subset(growth, Coral.species == "Pocillopora")
porites <- subset(growth, Coral.species == "Porites")

# check how many pocillopora survived to the end of the experiment
sum(pocillopora$Survived)/nrow(pocillopora) # only 37.5% of them did...
sum(porites$Survived)/nrow(porites) # whereas 96% of Porites did

# Analyzing corals separately
# Effects of treatment on porites growth, effects of treatment on time to failure for Pocillopora

# create subset of data using surviving corals
alive <- subset(growth, Survived == 1)

porites_growth_model <- glmmTMB(Net.change ~ Treatment * Snail + 
                     (1 | Colony.ID) + (1|Tank),
                     data = porites )
plot(simulateResiduals(porites_growth_model)) # no problems
summary(porites_growth_model) 
plot(allEffects(porites_growth_model))
Anova(porites_growth_model) 
# Response: Net.change
#                   Chisq Df Pr(>Chisq)    
# Treatment        1.3837  1     0.2395    
# Snail           25.4124  2  3.032e-06 ***
# Treatment:Snail  1.0221  2     0.5999  
r.squaredGLMM(porites_growth_model) # 0.18, 0.41
emmeans(porites_growth_model, pairwise ~ Snail | Treatment)
# $contrasts
# Treatment = Ambient:
#  contrast                 estimate   SE df t.ratio p.value
#  Control - Coralliophila    4.8968 1.24 81   3.945  0.0005
#  Control - Drupella         4.1439 1.24 81   3.338  0.0036
#  Coralliophila - Drupella  -0.7528 1.24 81  -0.607  0.8170
# 
# Treatment = Heated:
#  contrast                 estimate   SE df t.ratio p.value
#  Control - Coralliophila    3.1330 1.24 81   2.524  0.0358
#  Control - Drupella         3.0915 1.24 81   2.491  0.0389
#  Coralliophila - Drupella  -0.0415 1.24 81  -0.033  0.9994

emmeans(porites_growth_model, pairwise ~ Treatment | Snail)
# $contrasts
# Snail = Control:
#  contrast         estimate   SE df t.ratio p.value
#  Ambient - Heated   1.7817 1.24 79   1.435  0.1551
# 
# Snail = Coralliophila:
#  contrast         estimate   SE df t.ratio p.value
#  Ambient - Heated   0.0179 1.24 79   0.014  0.9885
# 
# Snail = Drupella:
#  contrast         estimate   SE df t.ratio p.value
#  Ambient - Heated   0.7293 1.24 79   0.588  0.5585
# 

porites_letters <- data.frame(
  Snail = rep( c("Control", "Coralliophila", "Drupella"), 2 ),
  Treatment = c(rep("Ambient", 3), rep("Heated", 3)),
  Letters = rep(c("a", "b", "b"), 2)
  
)

```

```{r plot porites growth, fig.height = 10, fig.width=18}
# Version 1
(growth_plot <- ggplot() +
  geom_boxplot(data = porites, aes(x = Snail, y = Net.change, colour = Snail), outlier.shape = NA) +
  geom_point(data = porites, aes(x = Snail, y = Net.change, colour = Snail), position = position_jitterdodge(0.3)) +
  geom_text(data = porites_letters, aes(x = Snail, y = 18, label = Letters), size = 10) +
  facet_wrap(~ Treatment,
             labeller = as_labeller(c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)"))) +
  scale_colour_manual(values = snail_colors,
                      labels = c("Control" = expression(atop("Control", "     n = 15")),
                                 "Coralliophila" = expression(atop(italic("Coralliophila"), "n = 15")),
                                 "Drupella" = expression(atop(italic("Drupella"), "     n = 15"))
                                 )
                      ) +
  scale_x_discrete(labels = c("Control" = "Control",
                              "Coralliophila" = expression(italic("Coralliophila")),
                              "Drupella" = expression(italic("Drupella"))
                              )
                   ) +
  labs(y = "Net Growth (% Change)", x = "", title = "a.") +
  my_theme +
  theme(legend.position = "right"))

```

```{r pocillopora time to failure}


pocillopora$Mortality <- ifelse(pocillopora$Survived == 1, 0, 1)


# specify 14 as Days.til.death for corals that survived throughout the duration of the experiment
pocillopora$Days.til.death[is.na(pocillopora$Days.til.death) & pocillopora$Mortality == 0] <- 13

# with cox proportional hazards model
cox_model <- coxme(Surv(Days.til.death, Mortality) ~ Snail * Treatment + 
                   (1 | Colony.ID) + (1 | Tank), data = pocillopora)
summary(cox_model)

# Random effects:
#                   Chisq    df         p   AIC   BIC
# Integrated loglik 50.10  7.00 1.381e-08 36.10 23.45
#  Penalized loglik 75.56 13.37 1.054e-10 48.82 24.67
# 
# Fixed effects:
#                                       coef exp(coef) se(coef)     z       p
# SnailCoralliophila                 -0.4514    0.6367   0.7675 -0.59 0.55647
# SnailDrupella                       1.8279    6.2211   0.6247  2.93 0.00343
# TreatmentHeated                     0.4516    1.5708   0.9082  0.50 0.61904
# SnailCoralliophila:TreatmentHeated  1.3015    3.6746   0.9370  1.39 0.16486
# SnailDrupella:TreatmentHeated       0.9316    2.5385   0.8128  1.15 0.25174

Anova(cox_model)

#                 Df   Chisq Pr(>Chisq)    
# Snail            2 35.3994  2.056e-08 ***
# Treatment        1  2.6532     0.1033    
# Snail:Treatment  2  2.1375     0.3434    




# fit model without random effects to visualize fixed effects
coxph_model <- coxph(Surv(Days.til.death, Mortality) ~ Snail * Treatment, data = pocillopora)
coxph_model # very similar results
anova(cox_model, coxph_model) # but differs significantly from model with random effects


# Check proportional hazards assumption
cox.zph(cox_model) # all good


# Plot Schoenfeld residuals
plot(cox.zph(cox_model)) # weakly nonlinear but not bad

emmeans(cox_model, pairwise ~ Snail | Treatment)
# $contrasts
# Treatment = Ambient:
#  contrast                 estimate    SE  df z.ratio p.value
#  Control - Coralliophila     0.451 0.768 Inf   0.588  0.8265
#  Control - Drupella         -1.828 0.625 Inf  -2.926  0.0096
#  Coralliophila - Drupella   -2.279 0.688 Inf  -3.312  0.0027
# 
# Treatment = Heated:
#  contrast                 estimate    SE  df z.ratio p.value
#  Control - Coralliophila    -0.850 0.536 Inf  -1.586  0.2517
#  Control - Drupella         -2.760 0.562 Inf  -4.907  <.0001
#  Coralliophila - Drupella   -1.909 0.520 Inf  -3.673  0.0007



emmeans(cox_model, pairwise ~ Treatment | Snail)
# $contrasts
# Snail = Control:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.452 0.908 Inf  -0.497  0.6190
# 
# Snail = Coralliophila:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -1.753 0.947 Inf  -1.852  0.0640
# 
# Snail = Drupella:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -1.383 0.817 Inf  -1.692  0.0906

```

```{r plot survival curves, fig.height = 10, fig.width=18}
# create newdata argument for survfit() to accound for interactions in data
newdata <- expand.grid(
  Snail = unique(pocillopora$Snail),
  Treatment = unique(pocillopora$Treatment)
)

# create survival curves for fixed effects
surv_fit <- survfit(coxph_model, newdata = newdata)


# extract data from surv_fit
surv_list <- lapply(1:nrow(newdata), function(i) {
  # Create descriptive label for strata
  strata_label <- paste0(newdata$Snail[i], "-", newdata$Treatment[i])
  
  snail <- newdata$Snail[i]
  
  treatment <- newdata$Treatment[i]
  
  
  # Create dataframe for each group's survival curve
  data.frame(
    Time = surv_fit$time,
    Surv = surv_fit$surv[, i],  # Survival probabilities
    Lower = surv_fit$lower[, i],  # Lower CI
    Upper = surv_fit$upper[, i],  # Upper CI
    Strata = strata_label,
    Snail = snail,
    Treatment = treatment
  )
})
# Combine into a single dataframe
surv_df <- do.call(rbind, surv_list)

# subset final timepoint values for letters dataframe
poc_surv_letters <- subset(surv_df, Time == 13)

# add letters for connecting letters
poc_surv_letters$Letters <- ifelse(poc_surv_letters$Snail == "Drupella", "b", "a")

# add x position for plot to be right after last day
poc_surv_letters$X <- 13.5

# create df for statistic info
survival_stats <- data.frame(
  Treatment = c("Ambient", "Heated"),
  Text = c("Temp: P = 0.12\nSnail: P < 0.0001\nInteraction: P = 0.36", "")
)


(poc_survival_plot <-
  ggplot(surv_df, aes(x = Time, y = Surv, color = Snail)) +
  geom_step(show.legend = FALSE) +  # Survival curve
  geom_ribbon(aes(ymin = Lower, ymax = Upper, fill = Snail, colour = NULL), alpha = 0.2) +
  facet_wrap(~ Treatment,
             labeller = as_labeller(c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)"))) +
  scale_colour_manual(values = snail_colors,
                      labels = c("Control" = expression(atop("Control", "     n = 12")),
                                 "Coralliophila" = expression(atop(italic("Coralliophila"), "n = 12")),
                                 "Drupella" = expression(atop(italic("Drupella"), "     n = 12"))
                                 )
                      ) +
  scale_fill_manual(values = snail_colors,
                      labels = c("Control" = expression(atop("Control", "     n = 12")),
                                 "Coralliophila" = expression(atop(italic("Coralliophila"), "n = 12")),
                                 "Drupella" = expression(atop(italic("Drupella"), "     n = 12"))
                                 )
                      ) +
  labs(
    x = "Days Until Death",
    y = "Survival Probability\n",
    title = "b."
    ) +
  geom_text(data = poc_surv_letters, aes(x = X, y = Surv, label = Letters), colour = "black", size = 10) +
  my_theme +
  theme(legend.position = "right"))

```

```{r coral growth and suvival panel, fig.height = 18, fig.width=20}
(growth_surv_panel <- ggarrange(growth_plot, poc_survival_plot, nrow = 2, ncol = 1, common.legend = F))

# I ANNOTATED THIS FURTHER IN PHOTOSHOP TO ADD RELEVANT STATISTICAL INFO TO BOTH PLOTS

# ggsave(here::here("output", "growth_survival_plot_v3.png"), growth_surv_panel, height = 18, width = 20)

```

```{r tissue loss}
# read data
tissue_long <- read.csv(here::here("data", "tissue_loss_image_analysis.csv"), stringsAsFactors = T)

# condense tissue loss data so that you have total surface area and lost surface area by summming all images
tissue <- tissue_long %>%
  group_by(Coral.species, Snail, Treatment, Coral.ID, Colony.ID) %>%
  summarise(Surface.area = sum(Live.tissue),
            Dead.area = sum(Dead.tissue))

# calculate percent mortality as dead tissue/live tissue
tissue$Mortality <- tissue$Dead.area/tissue$Surface.area

# photos were only taken of corals that did not experience 100% mortality at the end of the experiment
# fill in the remaining corals that are missing from this dataframe and specify that they had 100% mortality
# rough/bootleg way to do this

# set it so every coral ID in the meta df has a dummy mortality value of 1
growth_meta$Mortality_new <- 1

# merge new growth_meta with the tissue data so that we have a df with all coral IDs
tissue_full <- merge(
  growth_meta, 
  tissue[, c("Coral.ID", "Mortality")],  # Select only relevant columns from mortality_df
  by = "Coral.ID", 
  all.x = TRUE
)

# Fully dead corals should have NAs in mortality - fill with 1s instead to indicate total mortality
tissue_full$Mortality <- ifelse(is.na(tissue_full$Mortality), 1, tissue_full$Mortality)

# sv_transform mortality data because of 0s and 1s
tissue_full$Mortality_trans <- sv_trans(tissue_full$Mortality)

# porites rarely experience 100% mortality - separating out corals to analyze separately
porites_tissue <- subset(tissue_full, Coral.species == "Porites")
pocillopora_tissue <- subset(tissue_full, Coral.species == "Pocillopora")



### Porites model
# model with beta regression
porites_tissue_mod <- glmmTMB(Mortality_trans ~ Snail*Treatment + (1|Colony.ID) + (1|Tank),
                      family = beta_family(), data = porites_tissue)
summary(porites_tissue_mod)
Anova(porites_tissue_mod)
# Response: Mortality_trans
#                   Chisq Df Pr(>Chisq)    
# Snail           66.5636  2  3.515e-15 ***
# Treatment       12.0625  1  0.0005145 ***
# Snail:Treatment  0.3419  2  0.8428499    
plot(simulateResiduals(porites_tissue_mod)) # levene test for homogeneity significant - likely due to treatment effects
emmeans(porites_tissue_mod, pairwise ~ Snail | Treatment )

# $contrasts
# Treatment = Ambient:
#  contrast                 estimate    SE  df z.ratio p.value
#  Control - Coralliophila    -1.788 0.408 Inf  -4.388  <.0001
#  Control - Drupella         -2.468 0.432 Inf  -5.708  <.0001
#  Coralliophila - Drupella   -0.680 0.438 Inf  -1.552  0.2669
# 
# Treatment = Heated:
#  contrast                 estimate    SE  df z.ratio p.value
#  Control - Coralliophila    -2.088 0.421 Inf  -4.963  <.0001
#  Control - Drupella         -2.476 0.426 Inf  -5.810  <.0001
#  Coralliophila - Drupella   -0.388 0.398 Inf  -0.974  0.5935



emmeans(porites_tissue_mod, pairwise ~ Treatment | Snail ) # tissue loss exacerbated in heated treatment!!
# $contrasts
# Snail = Control:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.775 0.398 Inf  -1.949  0.0513
# 
# Snail = Coralliophila:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -1.075 0.436 Inf  -2.465  0.0137
# 
# Snail = Drupella:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.782 0.413 Inf  -1.895  0.0581

porites_tissue_letters <- data.frame(
  Snail = rep( c("Control", "Coralliophila", "Drupella"), 2 ),
  Treatment = c(rep("Ambient", 3), rep("Heated", 3)),
  Letters = rep(c("a", "b", "b"), 2)
  
)



### Pocillopora
pocillopora_tissue_mod <- glmmTMB(Mortality_trans ~ Snail*Treatment + (1|Colony.ID) + (1|Tank),
                      family = beta_family(), data = pocillopora_tissue)
summary(pocillopora_tissue_mod)
Anova(pocillopora_tissue_mod)
#                   Chisq Df Pr(>Chisq)   
# Snail           10.0059  2   0.006718 **
# Treatment        1.4477  1   0.228891   
# Snail:Treatment  1.5929  2   0.450927   
plot(simulateResiduals(pocillopora_tissue_mod))
# levene test for homogeneity significant - and non-normal residuals likely due to treatment effects
emmeans(pocillopora_tissue_mod, pairwise ~ Snail | Treatment )
# drupella is worse than both other treatments in ambient but not heated

# $contrasts
# Treatment = Ambient:
#  contrast                 estimate    SE  df z.ratio p.value
#  Control - Coralliophila   -0.0408 0.499 Inf  -0.082  0.9963
#  Control - Drupella        -1.3498 0.530 Inf  -2.548  0.0292
#  Coralliophila - Drupella  -1.3090 0.531 Inf  -2.467  0.0363
# 
# Treatment = Heated:
#  contrast                 estimate    SE  df z.ratio p.value
#  Control - Coralliophila   -0.6613 0.492 Inf  -1.345  0.3702
#  Control - Drupella        -1.1074 0.505 Inf  -2.191  0.0726
#  Coralliophila - Drupella  -0.4461 0.494 Inf  -0.903  0.6381

emmeans(pocillopora_tissue_mod, pairwise ~ Treatment | Snail )
# $contrasts
# Snail = Control:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.366 0.556 Inf  -0.659  0.5101
# 
# Snail = Coralliophila:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.987 0.576 Inf  -1.713  0.0867
# 
# Snail = Drupella:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated   -0.124 0.547 Inf  -0.227  0.8206

pocillopora_tissue_letters <- data.frame(
  Snail = rep( c("Control", "Coralliophila", "Drupella"), 2 ),
  Treatment = c(rep("Ambient", 3), rep("Heated", 3)),
  Letters = c(c("a", "a", "b"), c("a", "a", "a"))
  
)
```

```{r tissue loss plots, fig.height=8, fig.width=12}
(porites_tissue_loss <- ggplot() +
  geom_boxplot(data = porites_tissue, aes(x = Snail, y = Mortality, colour = Treatment), outlier.shape = NA) +
  geom_point(data = porites_tissue,
             aes(x = Snail, y = Mortality, colour = Treatment), position = position_jitterdodge(0.3)) +
  scale_colour_manual(values = c("Heated" = "#FE6100", "Ambient" = "#648FFF"),
                      labels = c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)")) +
  scale_x_discrete(labels = c("Control" = expression(atop("Control", "n = 15")),
                              "Coralliophila" = expression(atop(italic("Coralliophila"), "n = 15")),
                               "Drupella" = expression(atop(italic("Drupella"), "n = 15"))
                                 )) +
  labs(y = "Proportion Tissue Mortality\n", x = "", title = "a.") +
  geom_segment(aes(x = 1.8, xend = 2.2, y = 1.2, yend = 1.2)) +
  geom_text(aes(x = 2, y = 1.2, label = "*"), size = 14) +
  geom_text(data = porites_tissue_letters, aes(x = Snail, y = 1.1, label = Letters, colour = Treatment),
            position = position_dodge(0.75), size = 10, show.legend = F) +
   scale_y_continuous( breaks = seq(0,1,0.2)) +
  geom_text(aes(x = 0.5, y = 0.7, label = "Temp: P < 0.001\nSnail: P < 0.0001\nInteraction: P = 0.84"), hjust = 0, size = 10) + 
  my_theme)

(pocillopora_tissue_loss <- ggplot() +
  geom_boxplot(data = pocillopora_tissue, aes(x = Snail, y = Mortality, colour = Treatment), outlier.shape = NA) +
  geom_point(data = pocillopora_tissue,
             aes(x = Snail, y = Mortality, colour = Treatment), position = position_jitterdodge(0.3)) +
  scale_colour_manual(values = c("Heated" = "#FE6100", "Ambient" = "#648FFF"),
                      labels = c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)")) +
  scale_x_discrete(labels = c("Control" = expression(atop("Control", "n = 12")),
                              "Coralliophila" = expression(atop(italic("Coralliophila"), "n = 12")),
                               "Drupella" = expression(atop(italic("Drupella"), "n = 12"))
                                 )) +
  labs(y = "Proportion Tissue Mortality\n", x = "", title = "b.") +
  geom_text(data = pocillopora_tissue_letters, aes(x = Snail, y = 1.1, label = Letters, colour = Treatment),
            position = position_dodge(0.75), size = 10, show.legend = F) +
   scale_y_continuous( breaks = seq(0,1,0.2)) +
  geom_text(aes(x = 3.5, y = 0.2, label = "Temp: P = 0.23\nSnail: P = 0.006\nInteraction: P = 0.45"), hjust = 1, size = 10) + 
  my_theme)

```

```{r tissue loss plot, fig.height=14, fig.width=12}
(tissue_loss_panel <- ggarrange(porites_tissue_loss, pocillopora_tissue_loss, nrow = 2, ncol = 1, common.legend = T, legend = "bottom"))

# ggsave(here::here("output", "tissue_loss_panel_v2.png"), tissue_loss_panel, height = 14, width = 12)
```

```{r pocillopora wax dipping }
# read in data
poc_wax_images <- read.csv(here::here("data", "pocillopora_wax_dipped_corals_images.csv"))
poc_wax_images <- na.omit(poc_wax_images) # remove NAs from images that were not relevant for these analyses

# subset just the front and back and side images
poc_key_images <- subset(poc_wax_images, Image.number == 1 | Image.number == 3 | Image.number == 5)

# sum to get planar area
poc_front_back <- poc_key_images %>%
  group_by(Coral.ID) %>%
  summarise(Planar.area = sum(Area))

# read wax dip area
poc_wax_weights <- read.csv(here::here("data", "poc_wax_dipping.csv"))

# remove cracked corals
poc_wax_weights <- subset(poc_wax_weights, NOTES != "CRACKED")

# subset for only corals that have image data - two were missing for some reason
poc_wax_weights_subset <- poc_wax_weights[poc_wax_weights$Coral.ID %in% unique(poc_front_back$Coral.ID),]

poc_wax_area <- merge(poc_front_back, poc_wax_weights_subset, by = "Coral.ID")

# fit relationship of planar area to surface area to extract relationship
area_mod <- lm(Surface.area ~ Planar.area, poc_wax_area)
summary(area_mod) # intercept = 2.2198, slope = 0.9060
performance::r2(area_mod) # R2 = 0.608 - not great but good

```

```{r pocillopora biomass}
# get planar area from full tissue
poc_tissue_long <- subset(tissue_long, Coral.species == "Pocillopora")

# subset the relevant images and calculate planar area
poc_surv_front_back <- subset(poc_tissue_long, Image.number == 1 | Image.number == 3 | Image.number == 5) %>%
  group_by(Coral.ID) %>%
  summarise(Planar.area = sum(Live.tissue))

# merge with proportional mortality data
poc_surv_tissue <- merge(poc_surv_front_back,
                         pocillopora_tissue[pocillopora_tissue$Coral.ID %in% unique(poc_surv_front_back$Coral.ID),],
                         by = "Coral.ID")

# calculate surface area based on relationship between planar area and surface area from wax-dipped corals
poc_surv_tissue$Surface.area <- 2.2198 + 0.9060*poc_surv_tissue$Planar.area

# correct for proportional mortality - only include surviving tissue
poc_surv_tissue$Surface.area.corrected <- poc_surv_tissue$Surface.area*(1-poc_surv_tissue$Mortality)

# read biomass data
poc_biomass <- read.csv(here::here("data", "pocillopora_biomass.csv"))

# merge with surface area data 
poc_biomass_full <- merge(poc_surv_tissue, poc_biomass, by = "Coral.ID")
poc_biomass_full$Biomass <- poc_biomass_full$Tissue.weight/poc_biomass_full$Surface.area.corrected

# explore data for modeling - 18 ambient, 9 heated. Uneven distribution across snail treatments. Thinking wilcox test. 
table(poc_biomass_full$Snail, poc_biomass_full$Treatment)

bwplot(Biomass ~ Treatment | Snail, data = poc_biomass_full) # looks like two big outliers



hist(poc_biomass_full$Biomass)




```
```{r poc model}
# simplest
wilcox.test(Biomass ~ Treatment, poc_biomass_full) # P = 0.78

# mixed model
poc_bio_mod <- glmmTMB(Biomass ~ Treatment + (1|Colony.ID) + (1|Tank), family = Gamma("log"), data = poc_biomass_full[poc_biomass_full$Biomass < 0.03,])
plot(simulateResiduals(poc_bio_mod)) # outliers detected (as expected) but otherwise fine
summary(poc_bio_mod) # lots of variance in random effects - enhanced by uneven sample size
Anova(poc_bio_mod) # X2 = 0.55, P = 0.46
```


```{r porites biomass setup}
# Read surface arean and biomass data
porites_biomass <- read.csv(here::here("data", "porites_biomass.csv"))

# merge with mortality data
porites_biomass_full <- merge(porites_tissue, porites_biomass, by = "Coral.ID")

# correct foil-calculated SA with proportional mortality
porites_biomass_full$Surface.area.corrected <- porites_biomass_full$Area*(1-porites_biomass_full$Mortality)

# calculate tissue biomass - g cm-2
porites_biomass_full$Biomass <- porites_biomass_full$Tissue_weight/porites_biomass_full$Surface.area.corrected

# not corrected surface area
porites_biomass_full$Biomass_full <- porites_biomass_full$Tissue_weight/porites_biomass_full$Area

# remove corals that reached 100% mortality
porites_biomass_full <- na.omit(porites_biomass_full)

bwplot(Biomass ~ Treatment | Snail, data = porites_biomass_full) # 2-3 outliers
bwplot(Tissue_weight ~ Treatment | Snail, data = porites_biomass_full) # seems to be driven by surface area correction
bwplot(Biomass ~ Treatment , data = porites_biomass_full) # doesn't look significant

# seems that just going by whole surface area doesn't inflate values as much
bwplot(Biomass_full ~ Treatment | Snail, data = porites_biomass_full)


```

```{r porites biomass model}
# model with snail
por_bio_mod1 <- glmmTMB(Biomass ~ Treatment*Snail + (1|Colony.ID) + (1|Tank), family = Gamma("log"), data = porites_biomass_full)
plot(simulateResiduals(por_bio_mod1)) # no issues in residuals
summary(por_bio_mod1) # not much variance in random effects
Anova(por_bio_mod1)
#                  Chisq Df Pr(>Chisq)   
# Treatment       6.6856  1    0.00972 **
# Snail           0.5695  2    0.75221   
# Treatment:Snail 0.1667  2    0.92001 

# could probably remove snail interaction from model as it's not relevant to questions
por_bio_mod2 <- glmmTMB(Biomass ~ Treatment + (1|Colony.ID) + (1|Tank), family = Gamma("log"), data = porites_biomass_full)
plot(simulateResiduals(por_bio_mod2)) # no issues in residuals
summary(por_bio_mod2) # not much variance in random effects
Anova(por_bio_mod2) # X2 = 9.0, P = 0.002
```
```{r plot biomass}
(porites_biomass_plot <-
  ggplot() +
  geom_boxplot(data = porites_biomass_full, aes(x = Treatment, y = Biomass, colour = Treatment), outlier.shape = NA) +
  geom_point(data = porites_biomass_full,
             aes(x = Treatment, y = Biomass, colour = Treatment), position = position_jitterdodge(0.3)) +
  scale_colour_manual(values = c("Heated" = "#FE6100", "Ambient" = "#648FFF"),
                      labels = c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)")) +
  labs(y = expression(Biomass ~ (g ~ cm^-2)),
       x = "", title = "a.") +
  scale_x_discrete(labels = c("Heated" = "Heated (30.5°C)\nn = 40", "Ambient" = "Ambient (28.5°C)\nn = 45")) +
  geom_text(aes(x = 0.5, y = 0.0115, label = "GLMM\nX2 = 9.0, P = 0.002"), hjust = 0, size = 10) + 
  my_theme)

(pocillopora_biomass_plot <-
  ggplot() +
  geom_boxplot(data = poc_biomass_full,
               aes(x = Treatment, y = Biomass, colour = Treatment), outlier.shape = NA) +
  geom_point(data = poc_biomass_full,
             aes(x = Treatment, y = Biomass, colour = Treatment), position = position_jitterdodge(0.3)) +
  scale_colour_manual(values = c("Heated" = "#FE6100", "Ambient" = "#648FFF"),
                      labels = c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)")) +
  scale_x_discrete(labels = c("Heated" = "Heated (30.5°C)\nn = 9", "Ambient" = "Ambient (28.5°C)\nn = 18")) +
  labs(y = expression(Biomass ~ (g ~ cm^-2)),
       x = "", title = "b.") +
  geom_text(aes(x = 0.5, y = 0.03, label = "Wilxocon Rank Sum Test\nW = 75, P = 0.78"), hjust = 0, size = 10) + 
  my_theme)
```

```{r biomass panel, fig.height=14, fig.width=12}
(biomass_panel <- ggarrange(porites_biomass_plot, pocillopora_biomass_plot, nrow = 2, ncol = 1, common.legend = T, legend = "bottom"))

# ggsave(here::here("output", "biomass_panel_v1.png"), biomass_panel, height = 14, width = 12)
```

```{r snail feeding data setup}
feeding_base <- read.csv(here::here("data", "snail_feeding.csv"))
str(feeding_base)

# Controls had no snail --> NA
# Coralliophila never observed feeding on Pocillopora --> NA for faster removal
# Snail was removed and had respiration measured after coral died --> NA
# Remove NAs from dataset
feeding_subset <- na.omit(feeding_base)

# merge with coral metadata
meta_cols <- c("Coral.ID", "Coral.species", "Treatment", "Snail", "Colony.ID", "Tank")
coral_meta <- growth[,which(names(growth) %in% meta_cols)]
feeding_comb <- merge(feeding_subset, coral_meta, by = "Coral.ID")

# corals to be analyzed separately
porites_feeding <- subset(feeding_comb, Coral.species == "Porites")
pocillopora_feeding <- subset(feeding_comb, Coral.species == "Pocillopora")
```

```{r feeding models}
#### porites - model interaction between treatment and snail ####
# Coral ID nested in Colony ID, accounting for repeated measures
porites_feeding_mod <- glmmTMB(Feeding_binary ~ Treatment*Snail + (1|Tank) + (1|Colony.ID/Coral.ID),
                               family = binomial(), data = porites_feeding)
plot(simulateResiduals(porites_feeding_mod)) # no issues
summary(porites_feeding_mod)
Anova(porites_feeding_mod)
#                   Chisq Df Pr(>Chisq)    
# Treatment        3.3854  1  0.0657756 .  
# Snail           56.3149  1  6.174e-14 ***
# Treatment:Snail 12.3291  1  0.0004459 ***

# pairwise comparisons
emmeans(porites_feeding_mod, pairwise ~ Treatment | Snail) # significantly more likely to see drupella feeding in heated trt
# $contrasts
# Snail = Coralliophila:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated     1.26 0.782 Inf   1.617  0.1060
# 
# Snail = Drupella:
#  contrast         estimate    SE  df z.ratio p.value
#  Ambient - Heated    -2.29 0.628 Inf  -3.652  0.0003

emmeans(porites_feeding_mod, pairwise ~ Snail | Treatment) # but more likely to see Coralliophila feeding overall
# $contrasts
# Treatment = Ambient:
#  contrast                 estimate    SE  df z.ratio p.value
#  Coralliophila - Drupella     6.18 0.815 Inf   7.584  <.0001
# 
# Treatment = Heated:
#  contrast                 estimate    SE  df z.ratio p.value
#  Coralliophila - Drupella     2.63 0.669 Inf   3.927  0.0001

# extract emmeans for plotting
porites_feeding_emmeans <- as.data.frame(emmeans(porites_feeding_mod, pairwise ~ Treatment | Snail)$emmeans)

# backtransform emmeans to be on response scale
inv_logit <- function(x){
  exp(x)/(1+exp(x))
}

porites_feeding_emmeans$response <- inv_logit(porites_feeding_emmeans$emmean)
porites_feeding_emmeans$lower.CI <- inv_logit(porites_feeding_emmeans$asymp.LCL)
porites_feeding_emmeans$upper.CI <- inv_logit(porites_feeding_emmeans$asymp.UCL)

#### pocillopora - only drupella observed feeding, so only model treatment ####
# model convergence problem when I include colony ID - dropping from this model
# overspecified
pocillopora_feeding_mod <- glmmTMB(Feeding_binary ~ Treatment + (1|Tank) + (1|Coral.ID),
                               family = binomial(), data = pocillopora_feeding)
plot(simulateResiduals(pocillopora_feeding_mod)) # no issues
summary(pocillopora_feeding_mod)
Anova(pocillopora_feeding_mod) # X2 = 3.5, P = 0.062
# suggestive, but not significant

# extract plotting data as above with porites
pocillopora_feeding_emmeans <- as.data.frame(emmeans(pocillopora_feeding_mod, pairwise ~ Treatment )$emmeans)
pocillopora_feeding_emmeans$response <- inv_logit(pocillopora_feeding_emmeans$emmean)
pocillopora_feeding_emmeans$lower.CI <- inv_logit(pocillopora_feeding_emmeans$asymp.LCL)
pocillopora_feeding_emmeans$upper.CI <- inv_logit(pocillopora_feeding_emmeans$asymp.UCL)
```

```{r plot feeding behavior, fig.height  = 8, fig.width=8}
(porites_feeding_plot <-
  ggplot() +
  geom_point(data = porites_feeding_emmeans, aes(x = Snail, y = response, colour = Treatment), position = position_dodge(0.3),
             size = 5) +
  geom_errorbar(data = porites_feeding_emmeans, aes(x = Snail, ymin = lower.CI, ymax = upper.CI,
                                                    colour = Treatment), width = 0.3, position = position_dodge(0.3)) +
  scale_x_discrete(labels = c("Coralliophila" = expression(italic(Coralliophila)), "Drupella" = expression(italic(Drupella)))) +
  scale_colour_manual(values = c("Heated" = "#FE6100", "Ambient" = "#648FFF"),
                      labels = c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)")) +
  labs(y = expression(italic(P(Feeding))), title = "a.", x = "") + 
  geom_segment(aes(x = 1.8, xend = 2.2, y = 0.95, yend = 0.95)) +
  geom_text(aes(x = 2, y = 1, label = "***"), size = 8) +
  geom_text(aes(x = 0.5, y = 0.25, label = "Temp: P 0.07\nSnail:P < 0.001\nInteraction: P < 0.001"), size = 10, hjust = 0) +
  my_theme)
  
(pocillopora_feeding_plot <-
  ggplot() +
  geom_point(data = pocillopora_feeding_emmeans, aes(x = Treatment, y = response, colour = Treatment), position = position_dodge(0.3),
             size = 5) +
  geom_errorbar(data = pocillopora_feeding_emmeans, aes(x = Treatment, ymin = lower.CI, ymax = upper.CI,
                                                    colour = Treatment), width = 0.3, position = position_dodge(0.3)) +
  scale_x_discrete(labels = c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)")) +
  scale_colour_manual(values = c("Heated" = "#FE6100", "Ambient" = "#648FFF"),
                      labels = c("Heated" = "Heated (30.5°C)", "Ambient" = "Ambient (28.5°C)")) +
  labs(y = expression(italic(P(Feeding))), title = "b.", x = "") + 
  geom_text(aes(x = 0.5, y = 0.7, label = "GLMM\nX2 = 3.5, P = 0.06"), size = 10, hjust = 0) +
  my_theme)
```

```{r feeding panel, fig.height=14, fig.width=12}
(feeding_panel <- ggarrange(porites_feeding_plot, pocillopora_feeding_plot, nrow = 2, ncol = 1, common.legend = T, legend = "bottom"))

# ggsave(here::here("output", "feeding_panel_v1.png"), feeding_panel, height = 14, width = 12)
```

```{r ambient temp summary}
# read temp summary table from edi
temp_url <- "https://portal.edirepository.org/nis/dataviewer?packageid=knb-lter-mcr.1045.5&entityid=7a8090507e95d40ba98d837388f7c506"
temp <- read.csv(temp_url)
str(temp)
temp$date_local <- as.Date(temp$date_local) # convert date from chr to date

# filter for relevant dates - date when I arrived and last date of snail collection
entry <- "2024-04-27"
collection <- "2024-05-11"
temp_relev <- temp[temp$date_local >= entry & temp$date_local <= collection, ]
# View(temp_relev) # gather relevant data on median/mean temps for pub

```